# Enable the ability to ping players by saying their name in chat

# Placeholders:
# {USERNAME} - gets players IGN
# {UUID} - gets players UUID
# {DISPLAYNAME} - gets players nickname
# {ITEM} - gets the item in the players hand

ping:
  enable: true

  # Specify the format of the ping in chat.
  format: '&e@{DISPLAYNAME}'
  tooltip:
    - '&o{USERNAME}'

  # Require permission
  permission:
    use: false
    node: "chatpingerpro.ping"

item:
  enable: true

  # Specify the format of the item in chat.
  format: '&r<{ITEM}&r>'

  # Which words should be parsed as an item
  delimiter:
    - "[i]"
    - ".i"
    - "[item]"
    - ".item"
    - "[hand]"
    - ".hand"

  # Items that will not be parsed as an item
  blacklist:
    - AIR

  # Require permission
  permission:
    use: false
    node: "chatpingerpro.item"

inventory:
  enable: true

  # Specify the format of the inventory link in chat.
  format: '&r<{DISPLAYNAME}&r''s Inventory&r>'

  # Which words should be parsed as an inventory link
  delimiter:
    - "[inventory]"
    - ".inventory"
    - "[inv]"
    - ".inv"

  # Require permission
  permission:
    use: false
    node: "chatpingerpro.inventory"
