# Enable the ability to ping players by saying their name in chat

# Placeholders:
# {USERNAME} - gets players IGN
# {UUID} - gets players UUID
# {DISPLAYNAME} - gets players nickname

pings:
  enable: true

  # Specify the format of the ping in chat.
  format: '&e@{DISPLAYNAME}'
  tooltip:
    - '&o{USERNAME}'

  # Require permission
  permission:
    use: false
    node: "chatpingerpro.ping"
